// Plain-text and file-download export helpers for Mind Report.

import { LENSES } from '@/lib/lenses'
import type { MapResult } from '@/lib/reportTypes'

export function buildExportText(result: MapResult, lensLabel: string): string {
  const divider = '─'.repeat(56)
  const date    = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const sections = result.terrainMap
    .map((slice, i) => {
      const num     = String(i + 1).padStart(2, '0')
      const paras   = slice.body.split(/\n+/).map(p => p.trim()).filter(Boolean)
      const markers = slice.markers?.length ? `\nRecognition signals: ${slice.markers.join('  ·  ')}` : ''
      const prom    = slice.prominence === 'primary' ? ' [PRIMARY]' : ''
      return [
        `${num}. ${slice.label.toUpperCase()}${prom}`,
        `${slice.summary}`,
        '',
        paras.join('\n\n'),
        markers,
      ].filter(s => s !== undefined).join('\n')
    })
    .join(`\n\n${divider}\n\n`)

  const nowText        = result.nextMoveNow || result.nextMove || ''
  const structuralText = result.nextMoveStructural || ''

  return [
    'MIND REPORT',
    `${result.title}`,
    `${lensLabel} Lens  ·  ${date}`,
    '',
    divider,
    '',
    `"${result.quote}"`,
    '',
    divider,
    '',
    'CORE PATTERN',
    result.corePattern,
    '',
    divider,
    '',
    sections,
    '',
    divider,
    '',
    'HIDDEN COST',
    result.hiddenCost,
    '',
    ...(result.unseen ? ['WHAT YOU MAY NOT HAVE NOTICED', result.unseen, ''] : []),
    ...(nowText ? ['NEXT MOVE — THIS WEEK', nowText, ''] : []),
    ...(structuralText ? ['NEXT MOVE — BUILD TOWARD', structuralText, ''] : []),
    divider,
    '',
    'Generated by Mind Report  ·  mindreport.com',
    'This map reflects patterns in your words, not a clinical assessment.',
    'Take what is useful. Leave what does not fit.',
  ].join('\n')
}

export function buildAllExportText(maps: Record<string, MapResult>): string {
  const heavy     = '═'.repeat(56)
  const completed = LENSES.filter(l => maps[l.id])
  if (completed.length === 0) return ''
  if (completed.length === 1) return buildExportText(maps[completed[0].id], completed[0].label)
  const date   = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const header = `MIND REPORT  ·  ${completed.length} LENSES  ·  ${date}\n${heavy}\n`
  return header + '\n\n' + completed.map(l => buildExportText(maps[l.id], l.label)).join(`\n\n${heavy}\n\n`)
}

export function downloadText(text: string, filename: string) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}
