import { NextRequest, NextResponse } from 'next/server'

// ── Email delivery via Resend ─────────────────────────────────────────────────
// Setup (one-time):
//   1. Sign up at resend.com (free tier: 100 emails/day)
//   2. Add and verify your domain (mindreport.com) in the Resend dashboard
//   3. Add RESEND_API_KEY and RESEND_FROM_EMAIL to your Vercel environment variables
//
// RESEND_API_KEY  — from resend.com/api-keys
// RESEND_FROM_EMAIL — e.g. "Mind Report <noreply@mindreport.com>"
//   (domain must be verified in Resend, or use "onboarding@resend.dev" for testing)

export const maxDuration = 15

export async function POST(req: NextRequest) {
  const { RESEND_API_KEY, RESEND_FROM_EMAIL } = process.env

  if (!RESEND_API_KEY) {
    return NextResponse.json(
      { error: 'Email delivery is not configured yet. Set RESEND_API_KEY in your Vercel environment variables.' },
      { status: 503 },
    )
  }

  let body: { email?: string; shareUrl?: string; title?: string; lensLabel?: string }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid request.' }, { status: 400 })
  }

  const { email, shareUrl, title, lensLabel } = body

  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return NextResponse.json({ error: 'Please enter a valid email address.' }, { status: 400 })
  }

  if (!shareUrl) {
    return NextResponse.json({ error: 'Missing share URL.' }, { status: 400 })
  }

  const from = RESEND_FROM_EMAIL || 'Mind Report <onboarding@resend.dev>'
  const mapTitle = title || 'Your Mind Report'
  const lens = lensLabel ? `${lensLabel} Lens` : 'Psychological Map'

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${mapTitle}</title>
</head>
<body style="margin:0;padding:0;background:#F8F6F2;font-family:Georgia,'Times New Roman',serif;">
  <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background:#F8F6F2;padding:40px 16px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;width:100%;">

          <!-- Header -->
          <tr>
            <td style="padding-bottom:28px;">
              <p style="margin:0;font-family:'Courier New',monospace;font-size:9px;letter-spacing:.2em;text-transform:uppercase;color:#9B9690;">
                Mind Report &middot; ${lens}
              </p>
            </td>
          </tr>

          <!-- Card -->
          <tr>
            <td style="background:#FFFFFF;border:1px solid #E5E1DB;border-top:3px solid #6B6560;border-radius:3px;padding:36px 40px;">
              <p style="margin:0 0 6px;font-family:'Courier New',monospace;font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:#9B9690;">
                Your map has been drawn
              </p>
              <h1 style="margin:0 0 24px;font-family:Georgia,serif;font-size:26px;font-weight:bold;letter-spacing:-.02em;line-height:1.15;color:#1C1917;">
                ${mapTitle}
              </h1>
              <p style="margin:0 0 32px;font-family:Georgia,serif;font-style:italic;font-size:15px;line-height:1.7;color:#6B6560;">
                Your psychological map is ready. It's a precise cartographic read of the territory you described — not a diagnosis, not a verdict, but one accurate way of seeing what you shared.
              </p>
              <table cellpadding="0" cellspacing="0" role="presentation">
                <tr>
                  <td style="background:#3D3A36;border-radius:2px;padding:14px 28px;">
                    <a href="${shareUrl}" style="font-family:'Courier New',monospace;font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:#F0ECE4;text-decoration:none;font-weight:bold;">
                      Read Your Map &rarr;
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding-top:24px;">
              <p style="margin:0;font-family:'Courier New',monospace;font-size:8px;letter-spacing:.07em;color:#9B9690;line-height:1.8;">
                This map reflects patterns in your words, not a clinical assessment.<br>
                Take what is useful. Leave what does not fit.<br><br>
                Generated by <a href="https://mindreport.com" style="color:#9B9690;">Mind Report</a> &middot; Psychological cartography by ReLoHu&trade;
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`

  try {
    const { Resend } = await import('resend')
    const resend = new Resend(RESEND_API_KEY)

    const { error } = await resend.emails.send({
      from,
      to: email,
      subject: `Your Mind Report: ${mapTitle}`,
      html,
    })

    if (error) {
      console.error('[email]', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ ok: true })
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Failed to send email'
    console.error('[email]', msg)
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
